#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_next_frame_button_click( wxCommandEvent& event );
		void m_save_button_clicked( wxCommandEvent& event );
		void m_slider_change( wxScrollEvent& event );
		void m_circle_button_clicked( wxCommandEvent& event );
		void m_broken_line_button_clicked( wxCommandEvent& event );
		void m_curve_line_button_clicked( wxCommandEvent& event );
		void m_ellipse_button_clicked( wxCommandEvent& event );
		void m_square_button_clicked( wxCommandEvent& event );
		void m_triangle_button_clicked( wxCommandEvent& event );
		void m_fill_button_check( wxCommandEvent& event );
		void m_left_click_on_panel( wxMouseEvent& event );
		void m_mouse_on_panel_moved( wxMouseEvent& event );
		void m_right_click_on_panel( wxMouseEvent& event );
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members



};

#endif // __GUIMyFrame1__
